version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "@S0n3p4r!!"
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "@S0n3p4r!!"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  php:
    build: .
    container_name: php_app
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./index.php:/var/www/html/index.php
      - ./src/config:/var/www/html/src/config
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
